(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const c=document.querySelector(".header-form");document.querySelector(".theme-toggle-button");const i=document.querySelector(".tasks-list");function l(s){const t=JSON.parse(localStorage.getItem("tasks"))||[];t.push(s),localStorage.setItem("tasks",JSON.stringify(t))}function u(s){const r=(JSON.parse(localStorage.getItem("tasks"))||[]).filter((n,e)=>e!==s);localStorage.setItem("tasks",JSON.stringify(r))}function d(){const t=(JSON.parse(localStorage.getItem("tasks"))||[]).map(({title:r,description:n})=>`<li class="task-list-item">
          <button class="task-list-item-btn">Delete</button>
          <h3>${r}</h3>
          <p>${n}</p>
        </li>`).join("");i.insertAdjacentHTML("beforeend",t)}function m({title:s,description:t}){const r=`<li class="task-list-item">
          <button class="task-list-item-btn">Delete</button>
          <h3>${s}</h3>
          <p>${t}</p>
        </li>`;i.insertAdjacentHTML("beforeend",r)}d();c.addEventListener("submit",s=>{s.preventDefault();const t=s.target.taskName.value.trim(),r=s.target.taskDescription.value.trim();if(console.log(t),console.log(r),!t||!r)return alert("Заповніть всі поля");m({title:t,description:r}),l({title:t,description:r}),c.reset()});i.addEventListener("click",s=>{if(s.target.classList.contains("task-list-item-btn")){const t=s.target.closest(".task-list-item"),r=[...i.children].indexOf(t);u(r),t.remove()}});
//# sourceMappingURL=index.js.map
